version: '2.1'
services:
    app:
        build: ./app
        image: rodrigobento/app
        container_name: app
        depends_on:
            postgres:
                condition: service_healthy
        links:
            - "postgres:host-banco"
    postgres:
        build: ./postgres
        image: rodrigobento/banco
        container_name: banco
        ports:
            - "5433:5432"
        healthcheck:
            test: "exit 0"
